//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DignityHealth.WebApi.DWResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DWRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DWRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DignityHealth.WebApi.DWResources.DWRes", typeof(DWRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acknowledged.
        /// </summary>
        internal static string Acknowledged {
            get {
                return ResourceManager.GetString("Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1.
        /// </summary>
        internal static string AcknowledgeValues {
            get {
                return ResourceManager.GetString("AcknowledgeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asc.
        /// </summary>
        internal static string Asc {
            get {
                return ResourceManager.GetString("Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignedOnly.
        /// </summary>
        internal static string AssignedOnly {
            get {
                return ResourceManager.GetString("AssignedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarePartner.
        /// </summary>
        internal static string CarePartnerRole {
            get {
                return ResourceManager.GetString("CarePartnerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId.
        /// </summary>
        internal static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desc.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duenow.
        /// </summary>
        internal static string DueNow {
            get {
                return ResourceManager.GetString("DueNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male,Female.
        /// </summary>
        internal static string GenderValues {
            get {
                return ResourceManager.GetString("GenderValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or missing parameters.
        /// </summary>
        internal static string InvalidOrMissingParameters {
            get {
                return ResourceManager.GetString("InvalidOrMissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isacknowledged.
        /// </summary>
        internal static string IsAcknowledged {
            get {
                return ResourceManager.GetString("IsAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to istodayreminders.
        /// </summary>
        internal static string IsTodayReminders {
            get {
                return ResourceManager.GetString("IsTodayReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsViewed.
        /// </summary>
        internal static string IsViewed {
            get {
                return ResourceManager.GetString("IsViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyword.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string PatientRole {
            get {
                return ResourceManager.GetString("PatientRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommended.
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        internal static string Roster {
            get {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sortdirection.
        /// </summary>
        internal static string SortDirection {
            get {
                return ResourceManager.GetString("SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typeIds.
        /// </summary>
        internal static string TypeIds {
            get {
                return ResourceManager.GetString("TypeIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed values for {0} are {1}.
        /// </summary>
        internal static string ValidationAllowedValues {
            get {
                return ResourceManager.GetString("ValidationAllowedValues", resourceCulture);
            }
        }
    }
}
